server.port=8081

spring.data.mongodb.uri=mongodb+srv://kavindidewmini7_db_user:fmUFxow9kPoocfjd@onlinequizedb.zngioxc.mongodb.net/onlinequizedb?retryWrites=true&w=majority
spring.data.mongodb.database=onlinequizedb

app.jwt.secret=oqs_super_secure_secret_key_2026_very_long_string_123456
app.jwt.expMinutes=240